### PR TITLE
pytest-lazy-fixture v0.6.3 ❄️ 

### PR DESCRIPTION
**Pull request by lorepirri**
[PKG-3432] pytest-lazy-fixture 0.6.3 ❄️ 

- upstream: https://github.com/TvoroG/pytest-lazy-fixture/tree/v0.6.3
- dependency files:
    - https://github.com/TvoroG/pytest-lazy-fixture/blob/v0.6.3/setup.py
- conda-forge: https://github.com/conda-forge/pytest-lazy-fixture-feedstock/blob/main/recipe/meta.yaml

**Destination channel:** Snowflake

**Changes**
- fix recipe
- add abs file

**Dependency for**
- AnacondaRecipes/omegaconf-feedstock#2

[PKG-3432]: https://anaconda.atlassian.net/browse/PKG-3432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lorepirri** [comment]
After a successful build and upload to staging, I get a `cannot remove ‘<stuff>’: Permission denied` on the following platforms:

* `linux-64`
* `linux-aarch64`
* `linux-s390x`

Already notified sirius. It seems to me that it's a prefect problem

:prefect: https://cloud.prefect.io/anaconda/flow-run/974ea700-219d-44cf-bf2f-5792b97f0245

```                   INFO   Task 'remove_temp_directory': Starting task run...                                                                                                    
                   INFO   Removing directory /tmp/abs_97tg6_zojq                                                                                                                
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-310-pytest-7.4.0.pyc’: Permission denied                                 
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-38-pytest-7.4.0.pyc’: Permission denied                                  
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-39-pytest-7.4.0.pyc’: Permission denied                                  
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-311-pytest-7.4.0.pyc’: Permission denied                                 
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/v/cache/nodeids’: Permission denied                                                 
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/v/cache/stepwise’: Permission denied                                                
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/README.md’: Permission denied                                                       
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/.gitignore’: Permission denied                                                      
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/CACHEDIR.TAG’: Permission denied                                                    
                   ERROR  Command failed with exit code 1                                                                                                                       
                                                                                                                                                                                
                   INFO   Removing file /tmp/abs_prefect-x_s_rwok                                                                                                               
                   INFO   FAIL signal raised: FAIL('Command failed with exit code 1')                                                                                           
                   INFO   Task 'remove_temp_directory': Finished task run for task with final state: 'Retrying'                                                                 
11/22/23 10:51:23  INFO   Task 'remove_temp_directory': Starting task run...                                                                                                    
                   INFO   Removing directory /tmp/abs_97tg6_zojq                                                                                                                
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-310-pytest-7.4.0.pyc’: Permission denied                                 
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-38-pytest-7.4.0.pyc’: Permission denied                                  
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-39-pytest-7.4.0.pyc’: Permission denied                                  
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/__pycache__/test.cpython-311-pytest-7.4.0.pyc’: Permission denied                                 
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/v/cache/nodeids’: Permission denied                                                 
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/v/cache/stepwise’: Permission denied                                                
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/README.md’: Permission denied                                                       
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/.gitignore’: Permission denied                                                      
                   INFO   rm: cannot remove ‘/tmp/abs_97tg6_zojq/clone/recipe/.pytest_cache/CACHEDIR.TAG’: Permission denied                                                    
                   ERROR  Command failed with exit code 1                                                                                                                       
                                                                                                                                                                                
                   INFO   Removing file /tmp/abs_prefect-cdorqh9l                                                                                                               
                   INFO   FAIL signal raised: FAIL('Command failed with exit code 1')                                                                                           
                   INFO   Task 'remove_temp_directory': Finished task run for task with final state: 'Failed'                                                                   
                   INFO   Flow run FAILED: some reference tasks failed.                                                                                                         ```

**Review by cbouss — APPROVED** [review]
LGTM

**Comment by lorepirri** [comment]
I will wait for Sirius (Monday) for more information about the error with removing tmp directories.

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
@lorepirri I pushed a commit that should fix the issue.

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by lorepirri** [comment]
> @lorepirri I pushed a commit that should fix the issue.

thank you @JeanChristopheMorinPerso , nice catch, I totally missed that

**Pull request merged**
